[phases.setup]
nixPkgs = ['nodejs-18_x', 'python311', 'python311Packages.pip', 'python311Packages.venv']

[phases.install]
cmds = [
  'python3 -m venv /opt/venv',
  '. /opt/venv/bin/activate && pip install --no-cache-dir --extra-index-url https://d33sy5i8bnduwe.cloudfront.net/simple/ -r backend/requirements.txt',
  'npm install'
]

[phases.build] 
cmds = ['npm run build']

[start]
cmd = 'export PATH="/opt/venv/bin:$PATH" && sh start-railway.sh'