[phases.setup]
nixPkgs = ['nodejs-18_x', 'python311', 'python311Packages.pip']

[phases.install]
cmds = [
  'pip install --no-cache-dir --extra-index-url https://d33sy5i8bnduwe.cloudfront.net/simple/ -r backend/requirements.txt',
  'npm install --production'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'sh start-railway.sh'