[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.simple"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[variables]
NODE_ENV = "production"